import { Heading, Image, Stack, Text } from "rebar-ui";

export default function ArchetypesPage() {
  return (
    <Stack gap="lg" style={{ maxWidth: 720 }}>
      <Image src="/catalogue-heros/archetypes.jpeg" alt="Archetypes hero image" style={{ width: "100%", borderRadius: "8px" }} />

      <Heading level={1}>On Proprietary Disorder</Heading>

      <Text>
        We no longer look at screens; we are screen-bound, submerged in a hyperreal ocean where
        attention is not merely fractured, it is liquefied. The modern digital landscape is not a
        tool, but a terminal swamp of signals. We are battered not by singular catastrophes, but by
        a million micro-fractures of connectivity, trapped in a self-perpetuating wheel of noise. It
        is the illusion that chaos has become the default, raw creative engine of our age.
      </Text>

      <Heading level={2}>Proprietary Disorder and the System</Heading>

      <Text>
        Yet, this is merely the operational strategy of proprietary disorder. Disorder is no longer
        an accidental breakdown; it is manufactured, algorithmic, and systemic. A million microscopic
        failures are infinitely more efficient, more totalizing, than a single, marked disaster.
      </Text>

      <Text>
        What of a world that has institutionalized its own systemic malfunction, wherein disorder
        relentlessly begets disorder? The &quot;lords of discord&quot; are entirely irrelevant — they
        are merely the synthetic foam upon the surface of a much deeper sea. The digital epoch is
        that deep sea, the most treacherous simulation humanity has ever been asked to navigate.
        Traverse it we must, but so long as this sea remains engineered and volatile, our hope of
        ever passing beyond the digital age remains structurally null.
      </Text>

      <Heading level={2}>The Implosion of the Archetype</Heading>

      <Text>
        To diagnose this condition, we must abandon the naive belief in the &quot;real.&quot;
        Everything we encounter — from the linguistic utterance of a &quot;rock&quot; to a digital
        button that has long since ceased to be a lever — is an imitation, a layer of simulation. We
        live in a universe of pure signifiers severed from their referents. The button is no longer
        a physical mechanics of pressure; it is a sign of a sign. Nothing we touch, speak, or
        engineer retains an unmediated relationship to an archetype. Everything is a shadow cast by
        a model that no longer exists.
      </Text>

      <Text>
        And yet, chaos itself has no archetype. Disorder is not a creative force; it is a radical
        absence, a privation of being that wears the mask of hyperactive motion. Digital noise
        creates nothing new; it only accelerates the distortion of what was already given. Even the
        theological anchor — the reminder that chaos cannot create and that true stability resides in
        a divine reality — becomes another point of contrast against the endless desert of
        simulation.
      </Text>

      <Text>
        How, then, do we navigate a landscape of proprietary disorder and terminal simulation? We do
        not fall into the trap of utopian engineering, believing we can reform the hyperreal sea or
        code our way out of the machine. That illusion of total rescue is just another product
        generated by the system to keep us in perpetual motion.
      </Text>

      <Text>
        Instead, we embrace a different kind of fatal strategy: a clear-eyed patience with the
        terminal trajectory of our age. Modernity&apos;s grand project is a current that cannot be
        saved by its own momentum; it must run its course toward its own exhaustion. We do not try to
        out-engineer the simulation or smash the digital sea. Instead, we swim along the current of
        history, watching the system exhaust its own internal contradictions until it collapses under
        the weight of its own artifice.
      </Text>

      <Text>
        Yet, this stance is neither passive despair nor quietism. While we ride the current, we make
        things better as we go.
      </Text>

      <Text>
        We do not waste our strength attempting to calm the entire ocean through grand, abstract
        battles against the age. Instead, we tend to the local project. Through concrete acts of
        truth, kindness, and fidelity in our immediate circles, we refuse to let proprietary disorder
        code our reality. We are simply building small, durable things in the middle of the deluge,
        anchoring ourselves in an unshakeable ground that the simulation can neither manufacture nor
        destroy, waiting quietly for the system to wear itself out.
      </Text>

      <Heading level={2}>The articles</Heading>

      <Text>
        <a href="/archetypes/the-button" className="rebar-link">
          <strong>The Button</strong>
        </a>{" "}
        — from mechanical lever to switch to digital leverage. How the archetype of &quot;button&quot;
        is actually a &quot;lever,&quot; and why that physical ancestry still shapes the digital
        form&apos;s design today.
      </Text>
    </Stack>
  );
}
