import type { ComponentCounts } from "./useComponentCounts";

export type Complexity = "simple" | "medium" | "complex";

export const COMPLEXITY: Record<string, Complexity> = {
  box: "simple",
  stack: "simple",
  text: "simple",
  heading: "simple",
  button: "simple",
  input: "simple",
  card: "simple",
  alert: "simple",
  "form-item": "simple",
  checkbox: "simple",
  radio: "simple",
  switch: "simple",
  avatar: "simple",
  "aspect-ratio": "simple",
  progress: "simple",
  dialog: "medium",
  tabs: "medium",
  "radio-group": "medium",
  select: "medium",
  tooltip: "medium",
  popover: "medium",
  dropdown: "medium",
  slider: "medium",
  accordion: "medium",
  toast: "medium",
  carousel: "medium",
  form: "complex",
  divider: "simple",
  tag: "simple",
  badge: "simple",
  empty: "simple",
  skeleton: "simple",
  spin: "simple",
  breadcrumb: "simple",
  statistic: "simple",
  steps: "medium",
  result: "simple",
  descriptions: "simple",
  timeline: "simple",
  rate: "medium",
  navbar: "medium",
  "app-shell": "medium",
  "hover-card": "medium",
  "nav-index": "medium",
  "section-nav": "medium",
  wizard: "complex",
  "number-input": "simple",
  "pin-input": "medium",
  "segmented-control": "simple",
  editable: "medium",
  "color-picker": "medium",
  combobox: "complex",
  "multi-select": "medium",
  cascader: "complex",
  pagination: "simple",
  "tree-view": "complex",
  iframe: "simple",
  table: "complex",
  "scatter-chart": "medium",
  "line-chart": "medium",
  "stacked-bar-chart": "medium",
  "code-block": "simple",
  kanban: "complex",
  "card-kanban": "complex",
  "sticky-kanban": "complex",
  "theme-toggle": "medium",
  sticky: "simple",
  qrcode: "simple",
  barcode: "simple",
  "date-picker": "medium",
  image: "medium",
  lightbox: "simple",
  "file-upload": "complex",
  "bubble-chart": "medium",
  heatmap: "medium",
  "stacked-line-chart": "medium",
  "stacked-area-chart": "medium",
  "stepped-bar-chart": "medium",
  "step-chart": "medium",
  "index-chart": "medium",
  histogram: "medium",
  "ribbon-chart": "complex",
  "calendar-heatmap": "medium",
  "bullet-graph": "simple",
  "packed-bubble-chart": "complex",
  "umap-plot": "medium",
  "rich-text-editor": "complex",
  "pull-to-refresh": "medium",
  "picker-wheel": "medium",
  "swipe-actions": "medium",
  treemap: "medium",
  "candlestick-chart": "medium",
  "geo-chart": "medium",
  "gantt-chart": "complex",
  "sankey-diagram": "medium",
  "word-cloud": "medium",
  "node-link-graph": "complex",
  "data-grid": "complex",
  "pivot-table": "complex",
  "org-chart": "medium",
  "mind-map": "medium",
  flowchart: "medium",
  "diagram-minimap": "simple",
  popconfirm: "simple",
  "tree-select": "medium",
  tour: "complex",
  mentions: "medium",
  "back-top": "simple",
  affix: "medium",
  "avatar-group": "simple",
  "button-group": "simple",
  "speed-dial": "medium",
  masonry: "simple",
  collapsible: "simple",
  toggle: "simple",
  "toggle-group": "medium",
  "context-menu": "medium",
  menubar: "complex",
  "git-graph": "medium",
  "version-history": "medium",
  "chat-thread": "complex",
  "waveform-audio-player": "medium",
  "upload-queue": "medium",
  "infinite-scroll-grid": "medium",
  "goal-tracker": "complex",
  "text-to-speech-bar": "medium",
  "floating-selection-toolbar": "medium",
  "slash-command-menu": "medium",
  "voice-composer": "medium",
  "shape-gallery": "complex",
  "file-manager": "complex",
  "layers-panel": "complex",
  watermark: "simple",
  "bar-chart": "medium",
  "area-chart": "medium",
  sparkline: "simple",
  "pie-chart": "medium",
  "gauge-chart": "medium",
  "funnel-chart": "medium",
  "waterfall-chart": "medium",
  "radar-chart": "medium",
  "box-plot": "medium",
  drawer: "medium",
  "side-panel": "medium",
  footer: "simple",
  "scroll-mask": "medium",
  ellipsis: "medium",
  "floating-bubble": "medium",
  "floating-panel": "complex",
  "bottom-sheet": "medium",
  "action-sheet": "medium",
  "mobile-tab-bar": "medium",
  "scroll-area": "simple",
  "split-button": "medium",
  calendar: "complex",
  "time-picker": "medium",
  "resizable-panels": "complex",
  transfer: "complex",
  "command-palette": "complex",
};

const WEIGHT: Record<Complexity, number> = { simple: 1, medium: 2, complex: 3 };

export type MigrationEffort = "Low" | "Medium" | "High";

export interface MigrationEstimate {
  score: number;
  effort: MigrationEffort;
}

/**
 * A rough, configurable heuristic — not a measured cost. See ref/ASSESSMENT.md on why this
 * replaces the original brainstorm's fabricated token/dollar figures with a bucketed label
 * derived from real component counts instead.
 */
export function estimateMigrationEffort(counts: ComponentCounts): MigrationEstimate {
  let score = 0;
  for (const [type, count] of Object.entries(counts.byType)) {
    const complexity = COMPLEXITY[type] ?? "medium";
    score += WEIGHT[complexity] * count;
  }

  const effort: MigrationEffort = score < 10 ? "Low" : score < 30 ? "Medium" : "High";
  return { score, effort };
}
